name: Deploy

on:
  push:
    branches:
      - master

  release:
    types:
      - published

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Branch
      uses: actions/checkout@v2
      with:
        ref: master

    - name: Install Node
      uses: actions/setup-node@v1
      with:
        node-version: "18.x"

    - name: Install Hexo
      run: |
        export TZ='Asia/Taipei'
        npm install hexo-cli -g

    - name: Install Hexo
      uses: actions/cache@v1
      id: cache
      with:
        path: node_modules
        key: ${{runner.OS}}-${{hashFiles('**/package-lock.json')}}

    - name: Install Packages
      if: steps.cache.outputs.cache-hit != 'true'
      run: |
        npm install --save

    - name: Hexo Static Files Generation
      run: |
        hexo clean
        hexo generate

    - name: Deploy
      run: |
        cd ./public
        git init
        git config --global user.name '${{ secrets.GITHUBUSERNAME }}'
        git config --global user.email '${{ secrets.GITHUBEMAIL }}'
        git add .
        git commit -m "${{ github.event.head_commit.message }} $(date +"%Z %Y-%m-%d %A %H:%M:%S") Updated By Github Actions"
        git push --force --quiet "https://${{ secrets.GITHUBUSERNAME }}:${{ secrets.GITHUBTOKEN }}@github.com/${{ secrets.GITHUBUSERNAME }}/${{ secrets.GITHUBUSERNAME }}.github.io.git" master:gh-pages-2
        